server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
